# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10M2ZBjWM7M6Ffs5Qg3pcq__YnHeUCVdp
"""

!pip install streamlit
import streamlit as st
import pickle
import numpy as np

# Load trained model
model = pickle.load(open("logistic_model.pkl", "rb"))

st.set_page_config(page_title="Titanic Survival Prediction", layout="centered")

st.title("Titanic Survival Prediction App")
st.write("Enter passenger details to predict survival")

# User Inputs
pclass = st.selectbox("Passenger Class", [1, 2, 3])
age = st.number_input("Age", min_value=0, max_value=100, value=25)
fare = st.number_input("Fare", min_value=0.0, max_value=500.0, value=50.0)
sex = st.selectbox("Sex", ["Male", "Female"])
embarked = st.selectbox("Embarked", ["Q", "S", "C"])

# Encoding inputs
sex_male = 1 if sex == "Male" else 0
embarked_Q = 1 if embarked == "Q" else 0
embarked_S = 1 if embarked == "S" else 0

# Input array (must match training order)
input_data = np.array([[pclass, age, fare, sex_male, embarked_Q, embarked_S]])

# Prediction
if st.button("Predict Survival"):
    prediction = model.predict(input_data)

    if prediction[0] == 1:
        st.success(" Passenger Survived")
    else:
        st.error(" Passenger Did Not Survive")