# -*- coding: utf-8 -*-
"""stream_app.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CZPTk7ih-10DHYxuLcV3swPviyBS-VP2
"""

import streamlit as st
import pandas as pd
import pickle
import numpy as np

st.set_page_config(page_title="Titanic Survival Prediction App", layout="centered")

# ================================
# Load Trained Logistic Model
# ================================
@st.cache_resource
def load_model():
    model = pickle.load(open("logistic_model.pkl", "rb"))
    return model

model = load_model()

st.title("🚢 Titanic Survival Prediction App")
st.write("Enter passenger details to predict whether they survived or not.")

# ================================
# User Inputs
# ================================

# Passenger Class
pclass = st.selectbox("Passenger Class", [1, 2, 3])

# Sex
sex = st.selectbox("Sex", ["male", "female"])

# Age
age = st.slider("Age", 1, 90, 25)

# Fare
fare = st.number_input("Fare Paid", min_value=0.0, max_value=600.0, value=32.0)

# Embarked
embarked = st.selectbox("Port of Embarkation", ["S", "C", "Q"])

# ================================
# Preprocess Inputs for Model
# ================================

# Encode Sex
sex_encoded = 1 if sex == "female" else 0

# Encode Embarked (One-Hot)
embarked_S = 1 if embarked == "S" else 0
embarked_C = 1 if embarked == "C" else 0
embarked_Q = 1 if embarked == "Q" else 0

# Prepare input
input_data = np.array([[pclass, sex_encoded, age, fare, embarked_C, embarked_Q, embarked_S]])

# Column order MUST match training data
# ['Pclass', 'Sex', 'Age', 'Fare', 'Embarked_C', 'Embarked_Q', 'Embarked_S']


# ================================
# Prediction
# ================================
if st.button("Predict Survival"):
    prediction = model.predict(input_data)[0]
    prob = model.predict_proba(input_data)[0][1]

    st.subheader("Prediction Result")
    if prediction == 1:
        st.success(f"🎉 Survived! (Probability: {prob:.2f})")
    else:
        st.error(f"❌ Did Not Survive (Probability: {prob:.2f})")

# ================================
# Footer
# ================================
st.write("---")
st.caption("Titanic Logistic Regression Model • Streamlit App")